import requests, json
res = requests.post("http://localhost:5050/api/batch-predict", json={
    "photos": [{"label": "test", "image": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAAAAAAAD/2wBDAAoHBwgHBgoICAgLCgoLDhgQDg0NDh0VFhEYIx8lJCIfIiEmKzcvJik0KSEiMEExNDk7Pj4+JS5ESUM8SDc9Pjv/2wBDAQoLCw4NDhwQEBw7KCIoOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozv/wAARCABQAFADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAT/xAAdEAACAgMBAQEAAAAAAAAAAAAAAQIREiExUQMT/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQT/xAAZEQEBAQEBAQAAAAAAAAAAAAAAAQIDESH/2gAMAwEAAhEDEQA/APr0AFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/9k=", "lat": 1.23, "lng": 4.56}]
})
print(json.dumps(res.json(), indent=2))
